## Part 1: Preprocessing

In [34]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import layers

In [15]:
# # Import our dependencies
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler, OneHotEncoder
# import pandas as pd
# import numpy as np
# from tensorflow.keras.models import Model
# from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [3]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = pd.DataFrame([attrition_df['Attrition'], attrition_df['Department']])
y_df = y_df.transpose()
y_df

     Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [5]:
# Create a list of at least 10 column names to use as X data
X_names = ['BusinessTravel', 'DistanceFromHome', 'Education', 'EducationField', 'HourlyRate', 'NumCompaniesWorked', 'PerformanceRating', 'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager']


# Create X_df using your selected columns
X_df = attrition_df[X_names]

# Show the data types for X_df
X_df.dtypes

BusinessTravel             object
DistanceFromHome            int64
Education                   int64
EducationField             object
HourlyRate                  int64
NumCompaniesWorked          int64
PerformanceRating           int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)

In [19]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
X_to_encode = ['BusinessTravel', 'DistanceFromHome', 'Education', 'EducationField']


# encoder = OneHotEncoder(drop='first')
# column_transformer = ColumnTransformer(
#     transformers=[
#         ('cat', encoder, X_to_encode)
#     ],
#     remainder='passthrough'
# )
# train_encoded = column_transformer.fit_transform(X_train)
# test_encoded = column_transformer.transform(X_test)

# train_encoded_df = pd.DataFrame(train_encoded, columns=column_transformer.get_feature_names_out())
# test_encoded_df = pd.DataFrame(test_encoded, columns=column_transformer.get_feature_names_out())


df_train_one_hot = pd.get_dummies(X_train, columns=X_to_encode, drop_first=True)
df_test_one_hot = pd.get_dummies(X_test, columns=X_to_encode, drop_first=True)

ValueError: Shape of passed values is (1102, 1), indices imply (1102, 45)

In [26]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(df_train_one_hot)

# Scale the training and testing data
X_train_scaled = scaler.transform(df_train_one_hot)
X_test_scaled = scaler.transform(df_test_one_hot)

X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=df_train_one_hot.columns)
X_test_scaled_df = pd.DataFrame(X_test_scaled, columns=df_test_one_hot.columns)

In [51]:
X_train_scaled_df

,HourlyRate,NumCompaniesWorked,PerformanceRating,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,DistanceFromHome_2,DistanceFromHome_3,...,DistanceFromHome_29,Education_2,Education_3,Education_4,Education_5,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree
0,-0.325942,0.505016,-0.419635,-0.142174,-0.350760,-0.601092,-0.480921,0.648154,-0.41664,-0.248308,...,-0.121379,-0.482351,1.224282,-0.606008,-0.178424,-0.832334,-0.346293,-0.673666,-0.254429,3.131121
1,-0.572230,-1.093053,-0.419635,-0.483145,-0.350760,-0.885020,-0.480921,0.648154,-0.41664,4.027251,...,-0.121379,-0.482351,-0.816805,1.650143,-0.178424,-0.832334,-0.346293,1.484415,-0.254429,-0.319374
2,0.412925,-0.693536,-0.419635,-0.994602,-0.663492,-1.168948,2.079344,-1.542844,-0.41664,-0.248308,...,-0.121379,-0.482351,-0.816805,1.650143,-0.178424,1.201440,-0.346293,-0.673666,-0.254429,-0.319374
3,-0.030395,-0.294019,-0.419635,-0.142174,-0.663492,-0.885020,-0.480921,0.648154,-0.41664,-0.248308,...,-0.121379,-0.482351,-0.816805,1.650143,-0.178424,-0.832334,-0.346293,-0.673666,3.930364,-0.319374
4,1.201049,-0.294019,2.383021,-0.653631,-0.350760,-1.168948,-0.480921,0.648154,-0.41664,-0.248308,...,-0.121379,2.073180,-0.816805,-0.606008,-0.178424,1.201440,-0.346293,-0.673666,-0.254429,-0.319374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,0.905503,-0.693536,-0.419635,-0.142174,-0.350760,-0.601092,2.079344,-1.542844,-0.41664,-0.248308,...,-0.121379,-0.482351,-0.816805,1.650143,-0.178424,-0.832334,-0.346293,-0.673666,3.930364,-0.319374
1098,1.053276,0.105499,-0.419635,0.028311,-0.350760,0.818547,-0.480921,0.648154,-0.41664,-0.248308,...,-0.121379,-0.482351,1.224282,-0.606008,-0.178424,1.201440,-0.346293,-0.673666,-0.254429,-0.319374
1099,-1.360355,-0.693536,2.383021,2.415108,1.525635,0.818547,-0.480921,0.648154,-0.41664,-0.248308,...,-0.121379,2.073180,-0.816805,-0.606008,-0.178424,-0.832334,-0.346293,1.484415,-0.254429,-0.319374
1100,0.708471,0.904533,2.383021,1.733166,-0.350760,1.386403,-0.480921,0.648154,-0.41664,-0.248308,...,-0.121379,-0.482351,1.224282,-0.606008,-0.178424,-0.832334,2.887730,-0.673666,-0.254429,-0.319374
1101,0.609956,-0.693536,-0.419635,-0.994602,-0.663492,-1.168948,-0.480921,-1.542844,-0.41664,-0.248308,...,-0.121379,2.073180,-0.816805,-0.606008,-0.178424,1.201440,-0.346293,-0.673666,-0.254429,-0.319374

In [55]:
# Create a OneHotEncoder for the Department column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data
y_train_one_hot = pd.get_dummies(y_train, columns=['Department'], dtype='int')
y_test_one_hot = pd.get_dummies(y_test, columns=['Department'], dtype='int')

In [56]:
# Create a OneHotEncoder for the Attrition column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data
y_train_one_hot_2 = pd.get_dummies(y_train_one_hot, columns=['Attrition'], dtype='int')
y_test_one_hot_2 = pd.get_dummies(y_test_one_hot, columns=['Attrition'], dtype='int')

In [57]:
y_test_one_hot_2

,Department_Human Resources,Department_Research & Development,Department_Sales,Attrition_No,Attrition_Yes
1291,0,1,0,0,1
1153,0,0,1,0,1
720,0,1,0,0,1
763,0,0,1,1,0
976,0,1,0,1,0
...,...,...,...,...,...
78,0,1,0,1,0
1092,0,1,0,1,0
399,0,1,0,1,0
831,0,1,0,0,1
35,0,1,0,1,0

## Create, Compile, and Train the Model

In [37]:
# Find the number of columns in the X training data
print(len(X_train_scaled_df.columns))

# # Create the input layer
# model = Sequential()
# model.add(Dense(units=64, activation='relu', input_shape=(45,))
# # Create at least two shared layers
# model.add(Dense(units=48, activation='relu', input_shape=(45,))
# model.add(Dense(units=32, activation='relu', input_shape=(45,))

# Create the input layer
input_layer = Input(shape=(45,))
# Create at least two shared layers
shared_layer_1 = Dense(64, activation='relu')
shared_layer_2 = Dense(32, activation='relu')
shared_output_1 = shared_layer_1(input_layer)
shared_output_2 = shared_layer_2(shared_output_1)

45

In [40]:
# Create a branch for Department
# with a hidden layer and an output layer
department_layer = Dense(32, activation='relu')  #name='Department')
# Create the hidden layer
department_output_1 = department_layer(shared_output_2)

# Create the output layer
department_output_layer = Dense(3, activation='softmax', name='Department')
department_output_2 = department_output_layer(department_output_1)

In [43]:
# Create a branch for Attrition
# with a hidden layer and an output layer
attrition_layer = Dense(32, activation='relu')  #name='Attrition')
# Create the hidden layer
attrition_output_1 = attrition_layer(shared_output_2)

# Create the output layer
attrition_output_layer = Dense(1, activation='sigmoid', name='Attrition')
attrition_output_2 = attrition_output_layer(attrition_output_1)

In [44]:
# Create the model
model = Model(inputs=input_layer, outputs=[department_output_2, attrition_output_2])

# Compile the model
model.compile(optimizer='adam', loss={'Department': 'mse', 'Attrition': 'mse'})

# Summarize the model
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)      │ (None, 45)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense (Dense)                 │ (None, 64)                │           2,944 │ input_layer[0][0]          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_1 (Dense)               │ (None, 32)                │           2,080 │ dense[0][0]                │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_3 (Dense)               │ (None, 32)                │           1,056 │ dense_1[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_5 (Dense)               │ (None, 32)                │           1,056 │ dense_1[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ Department (Dense)            │ (None, 3)                 │              99 │ dense_3[0][0]              │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ Attrition (Dense)             │ (None, 1)                 │              33 │ dense_5[0][0]              │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 7,268 (28.39 KB)

 Trainable params: 7,268 (28.39 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
attrition_targets = y_train_one_hot_2[['Attrition_No', 'Attrition_Yes']]
department_targets = y_train_one_hot_2[['Department_Human Resources', 'Department_Research & Development', 'Department_Sales']]

# Train the model
model.fit(
    X_train_scaled_df,
    {'Attrition': attrition_targets, 'Department': department_targets},
    epochs=10,
    batch_size=32
)

Epoch 1/10

AttributeError: 'NoneType' object has no attribute 'items'

In [17]:
# Evaluate the model with the testing data

12/12 [==============================] - 0s 3ms/step - loss: 4.1624 - department_output_loss: 3.1143 - attrition_output_loss: 1.0481 - department_output_accuracy: 0.5272 - attrition_output_accuracy: 0.8261

[4.162380218505859,
 3.114327907562256,
 1.0480519533157349,
 0.5271739363670349,
 0.8260869383811951]

In [18]:
# Print the accuracy for both department and attrition

Department predictions accuracy: 0.5271739363670349
Attrition predictions accuracy: 0.8260869383811951

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. 
2. 
3.